name: Sync Vector Store

on:
  workflow_dispatch:    # manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload vector store to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.aws_githup_key }}
          source: "tenants/"
          target: "/home/ubuntu/lighchat/"